### ISSUE TITLE
Cannot read property 'values' of undefined, in debug=true mode

### ISSUE THREAD

**Issue by mani-mishra** [html-next/vertical-collection#51] opened 2017-04-24 19:09 UTC
When I pass debug= true,
I see the following error in console.
<img width="812" alt="screen shot 2017-04-25 at 12 36 35 am" src="https://cloud.githubusercontent.com/assets/3315240/25354071/2bb65f62-294f-11e7-8876-0578f4aa070c.png">

Wanted to debug why the implementation is not very smooth for us.
But with that error, the scrolling stutters even more.

Current invocation in our app.

```
{{#vertical-collection events
      classNames="vertical-collection__events-list"
      minHeight=200
      firstReached="loadAbove"
      lastReached="loadBelow"
      staticHeight=true
      bufferSize=4
      debug=true
      debugCSS=true
      as |event|
    }}

{{ our component}}
{{/vertical-collection}}
``` 

Granted our component is little on the heavier side, and there is too much stuff going on there. Is any anyway to speed the experience up?

**Comment by manimis902** [comment] 2017-04-24 19:36
I think we found the main reason for sluggishness. 
It takes a while to create all the elements in DOM. (we are only looping trying to show 100 elements though)

First set of around 10 elements are in list, but all other come up after some 10-15 seconds.

**Comment by pzuraq** [comment] 2017-04-24 19:43
yeah, I've been meaning to spend more time on the debugger, it's definitely not ready for v1.0.0 yet and very buggy. It'll get better before then.

So, your `bufferSize` is very large, you will actually be showing 9x the height of your container. So for instance if your container is 1000px high, you'd be rendering `(9 * 1000) / 200) + 1 = 46` components, which may be more than you need. One way to speed things up would be to decrease that size.

If you could provide an example of what your component code looks like (or something similar) I could try to help figure out ways to get some speedup from that as well!

**Comment by manimis902** [comment] 2017-04-24 19:45
Initially was using the default buffer size only. But on scrolling too fast, the container becomes empty and takes a while to render the new elements. So was trying with different options.

**Comment by pzuraq** [comment] 2017-04-24 19:54
Yeah, unfortunately fast scroll speeds can do that and there aren't many easy ways to throttle scroll 😕  (I'm planning on working on a wrapper component that will throttle scroll as a separate thing at some point)

Usually this will only cause a minor flicker except at the highest scroll speeds, and even then it tends to only be momentary. If you are experiencing long delays then it's likely because updating the components is taking a long time. This could be because of something we're doing wrong (we haven't done extensive testing with "heavy" components and want to add one to our dummy app to make sure that we're doing everything we can to make it as fast as possible) but if a component takes a while to render eventually it'll slow things down no matter what.

**Comment by pzuraq** [comment] 2017-07-15 23:49
Going to close this issue as a duplicate of #72 for the debugger stuff. For the perf issues, we've really tightened things up on the latest beta and master, so I'd recommend updating. `bufferSize` is also a lot more intuitive now, it will render at most `bufferSize` extra items on either side of the scroll container. If you'd like tips on how to make your components render fast let us know it #e-smoke-and-mirrors on the ember community slack!

**Closed by pzuraq** 2017-07-15 23:49 UTC
