### ISSUE TITLE
Attempt to remove scrollHandler failing in tests

### ISSUE THREAD

**Issue by kylemellander** [html-next/vertical-collection#146] opened 2017-10-18 17:08 UTC
Intermittently in tests, I get an error when using vertical collection with an error like this:

```
Error: Attempted to remove a handler from an unknown element or an element with no handlers
    at ScrollHandler.removeScrollHandler (-private.js:1756)
    at removeScrollHandler (-private.js:1817)
    at Class.willDestroy [as _super] (component.js:199)
    at Class.willDestroy (debug-mixin.js:82)
    at Class.superWrapper [as willDestroy] (ember-utils.js:426)
    at invokeWithOnError (backburner.js:283)
    at Queue.flush (backburner.js:153)
    at DeferredActionQueues.flush (backburner.js:345)
    at Backburner.end (backburner.js:455)
    at Backburner.run (backburner.js:533)
```

This is causing some of my async tests to fail.

**Comment by nragaz** [comment] 2017-10-18 17:15
Have you tried with the fix from #140 ?

**Comment by pzuraq** [comment] 2017-10-18 17:48
I'll release the fix today, just need to get #144 and #143 merged

**Comment by kylemellander** [comment] 2017-10-18 21:31
ahh!  glad to see its in the works - thanks for you work on this!

**Comment by miketervela** [comment] 2018-01-19 19:16
Still seeing this in Vertical-collection .9, did the fix get in there? Maybe I have configuration error

**Comment by pzuraq** [comment] 2018-01-25 02:04
@miketervela the bugfix should have made it in, is it the exact same issue? Stack trace and everything? If so, can you provide reproduction steps?

**Comment by miketervela** [comment] 2018-01-26 16:26
I actually haven't seen the trace since I posted that so it might have been tied to something else I was doing.

**Comment by pzuraq** [comment] 2018-01-27 01:14
Alright, going to close this for now. Please reopen if it pops up again!

**Closed by pzuraq** 2018-01-27 01:14 UTC

**Comment by miketervela** [comment] 2018-02-01 20:32
FYI, I did find the stack trace in an old issue of ours, but still haven't seen repeated in our dev or production since so I won't reopen the bug, just in case it's useful:
Error: Attempted to remove a handler from an unknown element or an element with no handlers
    at ScrollHandler.removeScrollHandler (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:141180:13)
    at removeScrollHandler (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:141241:12)
    at Class.willDestroy (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:141460:40)
    at Class.superFunction (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:28304:20)
    at Class.willDestroy (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:139120:12)
    at Class.superWrapper [as willDestroy] (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:32830:20)
    at invokeWithOnError (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:10584:18)
    at Queue.flush (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:10639:11)
    at DeferredActionQueues.flush (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:10440:17)
    at Backburner.end (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:9729:25)
    at Backburner.run (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:9842:18)
    at Object.run [as default] (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:30692:27)
    at Object.handler (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:34028:39)
    at HTMLAnchorElement.<anonymous> (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:56350:27)
    at HTMLBodyElement.dispatch (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:4778:9)
    at HTMLBodyElement.elemData.handle (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:4464:28)
    at HTMLBodyElement.nrWrapper (https://alpha.cloudfastpath.com/cfp/assets/vendor-dd217807975b3e7e0d9299d0d1269f51.js:115207:13841)
