### ISSUE TITLE
Vertical collection does not work very well with IE11 and Edge

### ISSUE THREAD

**Issue by jevanlingen** [html-next/vertical-collection#74] opened 2017-05-02 08:33 UTC
The plugin is just great in Chrome and Firefox. Sadly if I watch the [table demo](https://html-next.github.io/vertical-collection/#/examples/dbmon) in the Windows browsers, not so much.

**Internet Explorer 11**
First entries are loaded, but when scrolling down no new entries are drawn:
![image](https://cloud.githubusercontent.com/assets/1281763/25610101/2fdd14d6-2f22-11e7-9bd6-c1a87a398588.png)

**Edge**
Only first entry row is drawn (when scrolling up and down, all entries are drawn, so it seems some initialization error):

![image](https://cloud.githubusercontent.com/assets/1281763/25610156/6dd2b6a6-2f22-11e7-809f-7fa5f8ccbea5.png)

**Comment by runspired** [comment] 2017-05-02 21:33
Does this only happen on the table demo? Or on the other demos as well?

**Comment by jevanlingen** [comment] 2017-05-03 07:15
**Internet Explorer**
- Infinite Scroll: Same behaviour
- Flexible Layout: Demo does not start, only gray square is visible:
![image](https://cloud.githubusercontent.com/assets/1281763/25650983/c5b9e2e0-2fe0-11e7-8e70-842ea4673a09.png)
- Scrollable Body: Demo does not start, whole page stays white:
![image](https://cloud.githubusercontent.com/assets/1281763/25650996/da5eed44-2fe0-11e7-9054-b47eacc36c39.png)

**Edge**
- Other demos do work fine

**Comment by pzuraq** [comment] 2017-05-04 04:07
The issues with Edge are definitely related to the way tables render. Specifically, something to do with the way that we're adding VCs on initial render. If we populate the VC pool when we create the Radar, it renders like it should.

I can't seem to exactly reproduce the IE11 issues. For me, it renders the items, but doesn't update them on scroll.

Gotta handle some of the other issues, but edge and IE support are definitely a priority so will come back to this asap.

**Comment by pzuraq** [comment] 2017-05-24 17:13
IE11 should have been fixed by #92, still working on Edge so keeping this issue open

**Comment by kumkanillam** [comment] 2017-05-26 05:27
In IE-11 , I get the error `Unable to get property 'scrollTop' of undefined or null reference`.

![image](https://cloud.githubusercontent.com/assets/16604113/26481963/0caac042-4202-11e7-87fa-c2bf7bf289b1.png)

**Comment by pzuraq** [comment] 2017-05-26 06:02
It looks like you're using an older version, can you update to the latest master and see if it still happens? We should be releasing a new beta soon

**Comment by kumkanillam** [comment] 2017-05-26 11:09
I updated using this command `ember install git+https://github.com/html-next/vertical-collection.git#master`. 
Now I am receiving the below error,

```
app.js:106 Ember.onerror handler - error.message _verticalCollectionPrivate.Token is not a constructor  error TypeError: _verticalCollectionPrivate.Token is not a constructor
    at Class.init (component.js:235)
    at Class.superWrapper [as init] (ember.debug.js:40428)
    at new Class (ember.debug.js:36121)
    at Function._ClassMixinProps.create (ember.debug.js:36309)
    at CurlyComponentManager.create (ember.debug.js:12591)
    at OpenComponentOpcode.evaluate (ember.debug.js:47198)
    at VM.execute (ember.debug.js:53789)
    at VM.resume (ember.debug.js:53768)
    at TryOpcode.handleException (ember.debug.js:54279)
    at UpdatingVMFrame.handleException (ember.debug.js:54459)```

**Comment by pzuraq** [comment] 2017-05-26 14:54
That looks like a babel issue to me, we do some custom babel transforms to make everything faster when possible. What version of ember-cli are you using?

**Comment by runspired** [comment] 2017-05-26 16:07
ember-cli needs to be ~2.4 or later I believe

**Comment by pzuraq** [comment] 2017-05-26 17:35
For reference, we're running Ember-CLI 2.8 with Ember 1.8, so it's possible to use a much later version of CLI with earlier versions of Ember. I'd definitely be willing to help you figure out what's happening and fix it @kumkanillam, especially if it's on a more recent version of Ember-CLI

**Comment by kumkanillam** [comment] 2017-05-26 19:05
@pzuraq Sorry for the late reply. I am using 
ember-cli: 2.11.0
node: 6.3.1
os: win32 x64
"ember-source": "~2.11.0",
- For master, `ember install git+https://github.com/html-next/vertical-collection.git#master` I am getting the `_verticalCollectionPrivate.Token is not a constructor  error TypeError: _verticalCollectionPrivate.Token is not a constructor` in Chrome. 
-For latest version `ember install @html-next/vertical-collection@v1.0.0-beta.3 --save-dev` - no error came in Chrome but in IE I get  `Unable to get property 'scrollTop' of undefined or null reference.`

**Comment by pzuraq** [comment] 2017-05-26 19:11
yeah, the error you're getting on `beta.3` has likely been fixed in `master`. The error you're getting on master is very different, it looks like something strange is happening with your build that's causing our `-private` package to not exist. Can you post your `ember-cli-build`, and the other addons that you're using? If not, can you reproduce in a minimal example app so that we can try to debug this? Could also setup a screensharing session to dive in and take a look.

**Comment by kumkanillam** [comment] 2017-05-26 19:24
I will try it in brand new app, and let you know the status now.

**Comment by kumkanillam** [comment] 2017-05-26 20:14
@pzuraq  I created new app called `vc-test`, its working fine. it comes with `"ember-cli": "2.12.1"` but then when I change this to `"ember-cli": "2.11.0",` version by running the `npm install ember-cli@2.11.0 --save-dev`. I got the error in chrome. Is there any difference if I update ember-cli version alone without following proper update I haven't done `ember init` too.. I am ok to screensharing session if you want.

**Comment by kumkanillam** [comment] 2017-05-26 20:36
I can confirm that ember-cli version 2.11.0 is causing chrome error.

**Comment by pzuraq** [comment] 2017-05-26 20:38
Ok, I opened #96 to track this issue, looks like we have a bug with that specific version of ember-cli

**Comment by pzuraq** [comment] 2017-06-02 19:00
So now that `beta.4` is released I'm revisiting this, IE is throwing an error because something doesn't support an `includes` method, and Edge is failing on some examples due to measuring errors. The other issues mentioned seem to be resolved with the new rendering strategy, so going to dig into those and close this once we fix them.

**Comment by pzuraq** [comment] 2017-06-02 21:20
So it looks like IE/Edge do not have the same results for `Range.getBoundingClientRect` as every other browser. In IE, the blank text nodes surrounding each Virtual Component are seen as if they are immediately surrounding the _text_ content of the component, not the DOM nodes. The heights we get back are inaccurate because of this.

This is very problematic for our current measuring strategy, basically makes IE/Edge unusable with DynamicRadar. We'll have to figure out a workaround.

**Comment by pzuraq** [comment] 2017-06-30 17:24
So I'm going to attempt a refactor where we find and measure the root elements of each VC directly, and throw errors if any text nodes are included that aren't wrapped in an element and contain content of any kind. The alternative is to enforce one single root element, which may end up being what we have to do.

**Comment by pzuraq** [comment] 2017-07-15 23:44
Should be fixed now! Let me know if there are any more issues with IE/Edge. I'm going to try to get Saucelabs set asap so we are actually running the full test suite against all browsers.

**Closed by pzuraq** 2017-07-15 23:44 UTC
Labels: 1.0, bug, regression

**Comment by jevanlingen** [comment] 2017-08-18 10:18
@pzuraq: At the moment I used beta.7 in combination with Ember 2.12. Just upgraded to Ember 2.14. 

Everthing went fine, but stumbled at an IE error: `TypeError: Unable to get property 'source' of undefined or null reference`.

Are Ember 2.13 and 2.14 already fully supported btw? If I check the demo pages, Ember 2.12 is used there as well!

**Comment by pzuraq** [comment] 2017-09-07 18:21
They should be supported, I haven't encountered that issue with any version of Ember before, and we run all of our tests against the latest release, beta, and canary versions, although not in IE. Can you post steps to reproduce?

**Comment by jevanlingen** [comment] 2017-09-15 08:05
Ah just found the problem, I was missing some polyfills for IE. Just by adding
```javascript
'ember-cli-babel': {
    includePolyfill: true
}
```
to the [ ember-cli-build.js](https://github.com/babel/ember-cli-babel#polyfill) fixes the problems!

Apparently you need full polyfills to let vertical-collection work with the latest Ember versions. @pzuraq: Maybe this should be noted somewhere in the docs?

**Comment by pzuraq** [comment] 2017-09-15 17:43
The polyfills shouldn't be required, if we're relying on polyfilled APIs then we should probably figure out what APIs those are and fix them. Can you post reproduction steps so we can do that?

**Comment by pzuraq** [comment] 2017-09-15 17:43
I tried using the error message you posted above, I can't find anywhere in the source where we access a `source` property

**Comment by localpcguy** [comment] 2018-02-14 20:45
@pzuraq I ran into the `TypeError: Unable to get property 'source' of undefined or null reference` and it isn't actually in the VerticalCollection code, but it is being thrown BY the VerticalCollection code (if I remove the VerticalCollection the error disappears). It is in the [`meta` function in Ember's meta.js file](https://github.com/emberjs/ember.js/blob/756ef9f566e025fb0aa89ef85162c86bbd7598a4/packages/ember-metal/lib/meta.js#L554)

The check is for `undefined` specifically but `maybeMeta` is `null` when getting this error in IE11.

```
  // remove this code, in-favor of explicit parent
  if (maybeMeta !== undefined) {
    if (maybeMeta.source === obj) {
      return maybeMeta;
    }
    parent = maybeMeta;
  }
```

I'm not sure if it's actually a bug in Ember, or if VerticalCollection is somehow causing it to trigger.

**Comment by localpcguy** [comment] 2018-02-14 20:59
Adding the `includePolyfill` also fixed the issue, so I went looking in VerticalCollection, and I think the issue in IE11 might be the use of `.find` in [DynamicRadar (line 246)](https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/dynamic-radar.js#L246). [IE11 doesn't support `.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility) which has bitten me a number of times, and Babel doesn't transform it by default.

**Comment by localpcguy** [comment] 2018-02-14 21:39
Whoops, that my bad for assuming that `.find` was just the array function. Sorry.

Looking around some more, I also saw this which sets `__ember_meta_` to `null` - could that be where the `null` is coming from that errors in the `meta.js` file in Ember?

`this.__ember_meta__ = null;` in [radar.js](https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/radar.js#L126)

**Comment by pzuraq** [comment] 2018-02-14 21:44
ah, that is probably causing the issue. The reason for that is in Ember 1.11 we attempt to freeze the objects to make sure their shape is unchanged for perf, we can only do that in legacy Ember.

**Comment by localpcguy** [comment] 2018-02-14 21:53
Could it do something like the following? If that would work, I can probably do small PR for it if you'd like. 

```import { IS_GLIMMER_2, GTE_EMBER_1_13 } from 'ember-compatibility-helpers';
...
if (!GTE_EMBER_1_13) { 
   this.__ember_meta__ = null;
}```

Or it might be as simple as assigning it to `undefined` instead of `null`?
