### ISSUE TITLE
`key=` not working as expected

### ISSUE THREAD

**Issue by amk221** [html-next/vertical-collection#188] opened 2018-02-15 12:42 UTC
When specifying `key="@index"`, rows do not seem to be stabilising as expected (perhaps I am expecting the wrong thing?)

Please see this screencast and demo repo for an example:

https://github.com/amk221/-ember-vertical-collection-issue#ember-vertical-collection-issue

Each person has some tags. (Their ids match for the simplicity of the test case).
However, upon scrolling notice how the tag id no longer matches the person for that row.

**Comment by pzuraq** [comment] 2018-02-15 16:50
The issue you're having is caused by the fact that this computed property does not have any dependent keys: https://github.com/amk221/-ember-vertical-collection-issue/blob/master/app/components/person-tags.js#L7

Vertical collection recycles components, which means that you have 8 table rows that are never being fully destroyed or recreated. The computed property won't update unless you change something it's dependent on, `person` in this case. You can disable recycling for a performance hit by setting `shouldRecycle=false`.

**Comment by amk221** [comment] 2018-02-15 16:51
Yes, I thought that would be mentioned. Thought I'd check anyway

**Comment by runspired** [comment] 2018-02-15 22:31
Roughly speaking, `key` does the same for `{{each` as it does for `{{vertical-collection`.

In both cases it allows the diff algorithm to determine when an item in the previous state of the list matches an item in the new state of the list.

In the case of `{{each`, this happens to mean that any item that has a stable key from one state to the next state will have a component instance that is stable. Any item that does not will be a newly instantiated component.

In the case of `{{vertical-collection`, this means that any item that has a stable key from one state to the next state will have a state-object instance that is stable. Any item that does not will be a newly instantiated state-object.  It would defeat the purpose of recycling and infinite scroll to tie unique key to a unique component instance.

I don’t think that @amk221 wants to use `shouldRecycle: false` here, fundamentally his example app is just [a bad pattern that should be linted](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/require-dependent-keys.md).

Changing to the following would resolve the issue

```js
tags: computed('person.tags.length', function() {
    return this.get('person.tags').map(t => t.name);
})
```

If for some reason this to be very expensive and something that required more stability, moving this calculation higher up the chain would be better

e.g.

```ts
Person {
  tags = [];
  tagNames = computed('tags.length', function() { return this.tags.map(t => t.name); };
}
```

**Closed by runspired** 2018-02-15 22:31 UTC

**Comment by amk221** [comment] 2018-02-15 23:12
Thanks for the write up.

My use of computed with no dependant keys was intentional (I'm aware it would have been better in `init`). Uusing `key=` with `#each` results in the behaviour I expected (a new component instance, and therefore, the computed property computing again). So I think my point that `key=` doesn't do what I'd expect it to do in VC to be a valid one.
