### ISSUE TITLE
Custom key throws if items change too fast

### ISSUE THREAD

**Issue by makepanic** [html-next/vertical-collection#166] opened 2018-01-05 13:37 UTC
In an acceptance test i switch from 2 items to 0 which causes items to be empty but there are two scheduled actions `["lastVisibleChanged", 2], ["lastReached", 2]`.

This means it'll call `objectAt([], 2)` being undefined and `keyForItem(undefined, keyPath, index)` (which does `get(undefined, keyPath)` and in turn throws).

See https://github.com/html-next/vertical-collection/blob/b218268807b620854105ba76496844eb703d1959/addon/components/vertical-collection/component.js#L217

Is this a bug or am I doing something wrong?

**Comment by pzuraq** [comment] 2018-01-05 18:22
This is probably another instance of the bug caused by timing issues. #147 was a tentative fix, and we're seeing more and more of these issues so I'm going to give it another shot soon.

**Comment by pzuraq** [comment] 2018-01-27 01:21
The fix has been published for this in `v1.0.0-beta.10`! Can you verify that it's working when you get a chance?

**Comment by makepanic** [comment] 2018-01-29 18:09
Hey, I've updated to latest vertical-collection and I'm unable to reproduce the issue.

I guess this means the fix in beta.10 solved the issue :D

**Comment by pzuraq** [comment] 2018-01-29 18:10
Awesome, thanks for the quick response!

**Closed by pzuraq** 2018-01-29 18:10 UTC
